# Generated by Django 4.2.4 on 2023-08-22 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_user_photo_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profilePicture',
            field=models.FileField(default='C:\\Users\\hmira\\Documents\\Python\\preentrega3\\natureforce\\uploadedImages\\default_files\\default_profile.png', upload_to='uploadedImages/'),
        ),
    ]
