# Generated by Django 4.2.4 on 2023-08-29 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_user_profilepicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='description',
            field=models.TextField(default='A short description of the picture.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='user',
            name='profilePicture',
            field=models.FileField(default='C:\\Users\\hmira\\Documents\\Python\\natureforce\\uploadedImages\\default_files\\default_profile.png', upload_to='uploadedImages/'),
        ),
    ]
