# Generated by Django 4.2.4 on 2023-09-02 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_photo_description_alter_user_profilepicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='description',
            field=models.TextField(default='A short description of the picture.'),
        ),
    ]
