# Generated by Django 4.2.4 on 2023-09-04 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_alter_photo_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
