# Generated by Django 4.2.4 on 2023-09-10 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_avatar_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1000)),
                ('transmitter', models.CharField(max_length=250)),
                ('receiver', models.CharField(max_length=250)),
            ],
        ),
    ]
